### PR TITLE
Guard against destroyed object

### PR DESCRIPTION
**Pull request by zeppelin**
([Cultural reference](http://arresteddevelopment.wikia.com/wiki/J._Walter_Weatherman))

😄

### CODE REVIEW

**Comment by zeppelin** [comment]
Ember Concurrency spoiled us all... ;)

**Comment by zeppelin** [comment]
@balinterdi ping, i guess?

**Comment by balinterdi** [comment]
@zeppelin Thank you!

I indeed didn't see your PR (I still can't get used to the fact that GB doesn't make you watch your own repositories by default) and I just implemented something similar myself yesterday:
https://github.com/balinterdi/ember-cancelable-button/commit/7f111318c68704fde74312fdfbb2c6080b4db130

But I'll use your test (probably tomorrow) and see if my impl. is lacking, so thanks a bunch.

**Comment by zeppelin** [comment]
@balinterdi no worries, rebased. i might just stop contributing to new repos because gh ux is terrible and i waste my time most of the time. i overlooked so many good contribs in my repos as well for the same reason. although lesson learned: always mention the author right after submitting the pr...

**Comment by zeppelin** [comment]
also, tests are passing on my machine

**Comment by balinterdi** [comment]
Thanks! I've had the same happen to me with tests - they pass locally but fail on Travis, I'll have to look into that.

**Pull request merged**
